version: "3.9"

services:
  db:
    container_name: ies-bestrong-db
    image: mysql:5.7
    restart: always
    environment:

        MYSQL_DATABASE: ies-bestrong
        MYSQL_USER: user
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
    ports:
        - "9906:3306"
    volumes:
      - ./db:/db/mysql
    networks:
      my-network:
        ipv4_address: 172.18.0.6

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
    networks:
      my-network:
        ipv4_address: 172.18.0.7
#
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      my-network:
        ipv4_address: 172.18.0.8

  server:
    build:
      context: ./beStrong_server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ies-bestrong
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      URL_VM: http://172.18.0.9:8081
    restart: on-failure
    volumes:
      - ./beStrong_server:/var/lib/beStrong_server
    networks:
      my-network:
        ipv4_address: 172.18.0.9
  
  sensors:
    build:
      context: data_generation
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
      - server
    environment:
      RABBITMQ_IP: rabbit
      SERVER_IP: backend
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.18.0.10 
 
networks: 
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
