version: "3.9"

services:
  db:

    restart: always
    container_name: ies-bestrong-db
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: ies-bestrong
        MYSQL_USER: root
        MYSQL_PASSWORD: password
    ports:
        - "9906:3306"
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
#
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        #- 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq  

  server:
    build: #he “starter” dependenciesfor:→Spring Web, Spring Data JPA, MySQLdriver, DevToolsandValidation.Be sure to complete the following tasks[covered in the tutorial]:c)Create the Employee entity.
      context: beStrong_server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ies-bestrong
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq

    restart: on-failure

  sensors:
    build:
      context: data_generation
      dockerfile: Dockerfile
      
    links:
      - db
    depends_on:
      - db
      - rabbitmq
      - server
    environment:
      MY_SQL_IP: db
      RABBITMQ_IP: rabbitmq
      SERVER_IP: backend
    restart: on-failure
#
#  client:   
#    build:
#      context: beStrong_client
#      dockerfile: Dockerfile
#    ports: 
#      - '80:80'
#    depends_on:
#      - db
#      - rabbitmq
#      - server
#      - sensors
#    volumes: 
#      - ./src:/etc/share/nginx/html
#    environment:
#      SERVER_IP: backend
